language: python
python:
  - "2.7.14"
  - "2.7.14" # development branch
# command to install dependencies
install:
  - pip install -r requirements.txt
# no tests setup yet
# script:
#   - pytest
